export const accountsData = [
    { id: 1, accountName: "Freda", email: "freda03@fc2.com", phone: "5967957999", website: "http://sun.com", industry: "Real Estate", accountStatus: true, remark: "Active user" },
    { id: 2, accountName: "Aloysius", email: "aloy1@lyoos.com", phone: "4988111631", website: "http://51.la", industry: "Healthcare", accountStatus: false, remark: "Pending verification" },
    { id: 3, accountName: "Dalli", email: "dalli2@reference.com", phone: "9919131652", website: "http://walmart.com", industry: "Retail", accountStatus: false, remark: "Inactive account" },
    { id: 4, accountName: "Kort", email: "kort3@sakura.ne.jp", phone: "4928500329", website: "http://si.edu", industry: "Education", accountStatus: false, remark: "No remarks" },
    { id: 5, accountName: "Heall", email: "heall4@pinterest.com", phone: "3862338325", website: "https://amazon.com", industry: "E-commerce", accountStatus: false, remark: "New account" },
    { id: 6, accountName: "Sheeree", email: "sheeree5@bigcartel.com", phone: "4335161798", website: "https://huffingtonpost.com", industry: "Industrial", accountStatus: true, remark: "Verified account" },
    { id: 7, accountName: "Hildegarde", email: "hild6@mysql.com", phone: "8059906180", website: "https://yandex.ru", industry: "Cosmetics", accountStatus: true, remark: "Long-term user" },
    { id: 8, accountName: "Hulda", email: "hulda7@answers.com", phone: "8705495500", website: "https://mayoclinic.com", industry: "Machinery", accountStatus: true, remark: "No remarks" },
    { id: 9, accountName: "Shae", email: "shae8@google.pl", phone: "4628674456", website: "https://jugem.jp", industry: "IT Services", accountStatus: false, remark: "Inactive user" },
    { id: 10, accountName: "Jana", email: "jana9@wikispaces.com", phone: "4222905888", website: "https://si.edu", industry: "Consulting", accountStatus: true, remark: "Newly added" },
    { id: 11, accountName: "Gareth", email: "gareth10@gmail.com", phone: "6623456789", website: "http://apple.com", industry: "Tech", accountStatus: true, remark: "Premium user" },
    { id: 12, accountName: "Monica", email: "monica11@yahoo.com", phone: "7456789123", website: "https://samsung.com", industry: "Electronics", accountStatus: false, remark: "Subscription expired" },
    { id: 13, accountName: "Zara", email: "zara12@outlook.com", phone: "9876543210", website: "http://tesla.com", industry: "Automobile", accountStatus: true, remark: "Recently joined" },
    { id: 14, accountName: "Ben", email: "ben14@aol.com", phone: "3214567890", website: "https://ford.com", industry: "Manufacturing", accountStatus: false, remark: "Verification pending" },
    { id: 15, accountName: "Olivia", email: "olivia15@gmail.com", phone: "6547891234", website: "http://netflix.com", industry: "Entertainment", accountStatus: true, remark: "Active" },
    { id: 16, accountName: "Harrison", email: "harrison16@outlook.com", phone: "9785432106", website: "https://adidas.com", industry: "Fashion", accountStatus: false, remark: "Inactive account" },
    { id: 17, accountName: "Sophia", email: "sophia17@gmail.com", phone: "9876123456", website: "http://nike.com", industry: "Sports", accountStatus: true, remark: "Long-time user" },
    { id: 18, accountName: "Elliot", email: "elliot18@icloud.com", phone: "8123456789", website: "https://ibm.com", industry: "Tech", accountStatus: false, remark: "Pending approval" },
    { id: 19, accountName: "Daniel", email: "daniel19@yahoo.com", phone: "6549873210", website: "http://oracle.com", industry: "Software", accountStatus: true, remark: "Business account" },
    { id: 20, accountName: "Emma", email: "emma20@gmail.com", phone: "4321098765", website: "https://sony.com", industry: "Media", accountStatus: true, remark: "Verified" },
    { id: 21, accountName: "Lucas", email: "lucas21@msn.com", phone: "7689543210", website: "http://uber.com", industry: "Transportation", accountStatus: false, remark: "Inactive" },
    { id: 22, accountName: "Noah", email: "noah22@icloud.com", phone: "9821345678", website: "https://cisco.com", industry: "Networking", accountStatus: true, remark: "Premium user" },
    { id: 23, accountName: "Ava", email: "ava23@gmail.com", phone: "6758493210", website: "http://pepsi.com", industry: "Food & Beverage", accountStatus: false, remark: "Suspended" },
    { id: 24, accountName: "Mia", email: "mia24@outlook.com", phone: "5432167890", website: "https://lg.com", industry: "Electronics", accountStatus: true, remark: "Recently joined" },
    { id: 25, accountName: "Liam", email: "liam25@gmail.com", phone: "7654893210", website: "http://nike.com", industry: "Sportswear", accountStatus: true, remark: "VIP member" }
];
